
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserRole = {
  admin: 'admin',
  contractor: 'contractor',
  driver: 'driver'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]


export const VehicleWheel = {
  V4: '4',
  V6: '6',
  V10: '10',
  V12: '12'
} as const

export type VehicleWheel = (typeof VehicleWheel)[keyof typeof VehicleWheel]


export const GoodsType = {
  HANDLE_WITH_CARE: 'handlewithcare',
  AUTOMOBILE: 'automobile'
} as const

export type GoodsType = (typeof GoodsType)[keyof typeof GoodsType]


export const VehicleCategory = {
  OPEN: 'open',
  SEMIOPEN: 'semiopen',
  CONTAINER: 'container'
} as const

export type VehicleCategory = (typeof VehicleCategory)[keyof typeof VehicleCategory]


export const InsuranceType = {
  BASIC: 'basic',
  PRO: 'pro',
  MAXSAVER: 'maxsaver'
} as const

export type InsuranceType = (typeof InsuranceType)[keyof typeof InsuranceType]
