
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Contract` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Contract
 * 
 */
export type ContractModel = runtime.Types.Result.DefaultSelection<Prisma.$ContractPayload>

export type AggregateContract = {
  _count: ContractCountAggregateOutputType | null
  _avg: ContractAvgAggregateOutputType | null
  _sum: ContractSumAggregateOutputType | null
  _min: ContractMinAggregateOutputType | null
  _max: ContractMaxAggregateOutputType | null
}

export type ContractAvgAggregateOutputType = {
  id: number | null
  weight: number | null
  approxKms: number | null
  contractorId: number | null
  goodsCarrierId: number | null
  winningPrice: number | null
}

export type ContractSumAggregateOutputType = {
  id: number | null
  weight: number | null
  approxKms: number | null
  contractorId: number | null
  goodsCarrierId: number | null
  winningPrice: number | null
}

export type ContractMinAggregateOutputType = {
  id: number | null
  weight: number | null
  pickupDate: Date | null
  dropDate: Date | null
  startLocation: string | null
  endLocation: string | null
  approxKms: number | null
  contractorId: number | null
  goodsCarrierId: number | null
  typeOfVehicle: $Enums.VehicleWheel | null
  insured: boolean | null
  winningPrice: number | null
  type: $Enums.GoodsType | null
  createdAt: Date | null
  description: string | null
}

export type ContractMaxAggregateOutputType = {
  id: number | null
  weight: number | null
  pickupDate: Date | null
  dropDate: Date | null
  startLocation: string | null
  endLocation: string | null
  approxKms: number | null
  contractorId: number | null
  goodsCarrierId: number | null
  typeOfVehicle: $Enums.VehicleWheel | null
  insured: boolean | null
  winningPrice: number | null
  type: $Enums.GoodsType | null
  createdAt: Date | null
  description: string | null
}

export type ContractCountAggregateOutputType = {
  id: number
  weight: number
  pickupDate: number
  dropDate: number
  startLocation: number
  endLocation: number
  approxKms: number
  contractorId: number
  goodsCarrierId: number
  typeOfVehicle: number
  insured: number
  winningPrice: number
  type: number
  createdAt: number
  description: number
  requirements: number
  _all: number
}


export type ContractAvgAggregateInputType = {
  id?: true
  weight?: true
  approxKms?: true
  contractorId?: true
  goodsCarrierId?: true
  winningPrice?: true
}

export type ContractSumAggregateInputType = {
  id?: true
  weight?: true
  approxKms?: true
  contractorId?: true
  goodsCarrierId?: true
  winningPrice?: true
}

export type ContractMinAggregateInputType = {
  id?: true
  weight?: true
  pickupDate?: true
  dropDate?: true
  startLocation?: true
  endLocation?: true
  approxKms?: true
  contractorId?: true
  goodsCarrierId?: true
  typeOfVehicle?: true
  insured?: true
  winningPrice?: true
  type?: true
  createdAt?: true
  description?: true
}

export type ContractMaxAggregateInputType = {
  id?: true
  weight?: true
  pickupDate?: true
  dropDate?: true
  startLocation?: true
  endLocation?: true
  approxKms?: true
  contractorId?: true
  goodsCarrierId?: true
  typeOfVehicle?: true
  insured?: true
  winningPrice?: true
  type?: true
  createdAt?: true
  description?: true
}

export type ContractCountAggregateInputType = {
  id?: true
  weight?: true
  pickupDate?: true
  dropDate?: true
  startLocation?: true
  endLocation?: true
  approxKms?: true
  contractorId?: true
  goodsCarrierId?: true
  typeOfVehicle?: true
  insured?: true
  winningPrice?: true
  type?: true
  createdAt?: true
  description?: true
  requirements?: true
  _all?: true
}

export type ContractAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Contract to aggregate.
   */
  where?: Prisma.ContractWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contracts to fetch.
   */
  orderBy?: Prisma.ContractOrderByWithRelationInput | Prisma.ContractOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ContractWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contracts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contracts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Contracts
  **/
  _count?: true | ContractCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ContractAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ContractSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ContractMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ContractMaxAggregateInputType
}

export type GetContractAggregateType<T extends ContractAggregateArgs> = {
      [P in keyof T & keyof AggregateContract]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateContract[P]>
    : Prisma.GetScalarType<T[P], AggregateContract[P]>
}




export type ContractGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContractWhereInput
  orderBy?: Prisma.ContractOrderByWithAggregationInput | Prisma.ContractOrderByWithAggregationInput[]
  by: Prisma.ContractScalarFieldEnum[] | Prisma.ContractScalarFieldEnum
  having?: Prisma.ContractScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ContractCountAggregateInputType | true
  _avg?: ContractAvgAggregateInputType
  _sum?: ContractSumAggregateInputType
  _min?: ContractMinAggregateInputType
  _max?: ContractMaxAggregateInputType
}

export type ContractGroupByOutputType = {
  id: number
  weight: number
  pickupDate: Date
  dropDate: Date
  startLocation: string
  endLocation: string
  approxKms: number
  contractorId: number
  goodsCarrierId: number | null
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice: number | null
  type: $Enums.GoodsType
  createdAt: Date
  description: string
  requirements: string[]
  _count: ContractCountAggregateOutputType | null
  _avg: ContractAvgAggregateOutputType | null
  _sum: ContractSumAggregateOutputType | null
  _min: ContractMinAggregateOutputType | null
  _max: ContractMaxAggregateOutputType | null
}

type GetContractGroupByPayload<T extends ContractGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ContractGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ContractGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ContractGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ContractGroupByOutputType[P]>
      }
    >
  >



export type ContractWhereInput = {
  AND?: Prisma.ContractWhereInput | Prisma.ContractWhereInput[]
  OR?: Prisma.ContractWhereInput[]
  NOT?: Prisma.ContractWhereInput | Prisma.ContractWhereInput[]
  id?: Prisma.IntFilter<"Contract"> | number
  weight?: Prisma.FloatFilter<"Contract"> | number
  pickupDate?: Prisma.DateTimeFilter<"Contract"> | Date | string
  dropDate?: Prisma.DateTimeFilter<"Contract"> | Date | string
  startLocation?: Prisma.StringFilter<"Contract"> | string
  endLocation?: Prisma.StringFilter<"Contract"> | string
  approxKms?: Prisma.IntFilter<"Contract"> | number
  contractorId?: Prisma.IntFilter<"Contract"> | number
  goodsCarrierId?: Prisma.IntNullableFilter<"Contract"> | number | null
  typeOfVehicle?: Prisma.EnumVehicleWheelFilter<"Contract"> | $Enums.VehicleWheel
  insured?: Prisma.BoolFilter<"Contract"> | boolean
  winningPrice?: Prisma.IntNullableFilter<"Contract"> | number | null
  type?: Prisma.EnumGoodsTypeFilter<"Contract"> | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFilter<"Contract"> | Date | string
  description?: Prisma.StringFilter<"Contract"> | string
  requirements?: Prisma.StringNullableListFilter<"Contract">
  contractor?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  goodsCarrier?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  bids?: Prisma.BidListRelationFilter
  insurance?: Prisma.XOR<Prisma.InsuranceNullableScalarRelationFilter, Prisma.InsuranceWhereInput> | null
}

export type ContractOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  pickupDate?: Prisma.SortOrder
  dropDate?: Prisma.SortOrder
  startLocation?: Prisma.SortOrder
  endLocation?: Prisma.SortOrder
  approxKms?: Prisma.SortOrder
  contractorId?: Prisma.SortOrder
  goodsCarrierId?: Prisma.SortOrderInput | Prisma.SortOrder
  typeOfVehicle?: Prisma.SortOrder
  insured?: Prisma.SortOrder
  winningPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  description?: Prisma.SortOrder
  requirements?: Prisma.SortOrder
  contractor?: Prisma.UserOrderByWithRelationInput
  goodsCarrier?: Prisma.UserOrderByWithRelationInput
  bids?: Prisma.BidOrderByRelationAggregateInput
  insurance?: Prisma.InsuranceOrderByWithRelationInput
}

export type ContractWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ContractWhereInput | Prisma.ContractWhereInput[]
  OR?: Prisma.ContractWhereInput[]
  NOT?: Prisma.ContractWhereInput | Prisma.ContractWhereInput[]
  weight?: Prisma.FloatFilter<"Contract"> | number
  pickupDate?: Prisma.DateTimeFilter<"Contract"> | Date | string
  dropDate?: Prisma.DateTimeFilter<"Contract"> | Date | string
  startLocation?: Prisma.StringFilter<"Contract"> | string
  endLocation?: Prisma.StringFilter<"Contract"> | string
  approxKms?: Prisma.IntFilter<"Contract"> | number
  contractorId?: Prisma.IntFilter<"Contract"> | number
  goodsCarrierId?: Prisma.IntNullableFilter<"Contract"> | number | null
  typeOfVehicle?: Prisma.EnumVehicleWheelFilter<"Contract"> | $Enums.VehicleWheel
  insured?: Prisma.BoolFilter<"Contract"> | boolean
  winningPrice?: Prisma.IntNullableFilter<"Contract"> | number | null
  type?: Prisma.EnumGoodsTypeFilter<"Contract"> | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFilter<"Contract"> | Date | string
  description?: Prisma.StringFilter<"Contract"> | string
  requirements?: Prisma.StringNullableListFilter<"Contract">
  contractor?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  goodsCarrier?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  bids?: Prisma.BidListRelationFilter
  insurance?: Prisma.XOR<Prisma.InsuranceNullableScalarRelationFilter, Prisma.InsuranceWhereInput> | null
}, "id">

export type ContractOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  pickupDate?: Prisma.SortOrder
  dropDate?: Prisma.SortOrder
  startLocation?: Prisma.SortOrder
  endLocation?: Prisma.SortOrder
  approxKms?: Prisma.SortOrder
  contractorId?: Prisma.SortOrder
  goodsCarrierId?: Prisma.SortOrderInput | Prisma.SortOrder
  typeOfVehicle?: Prisma.SortOrder
  insured?: Prisma.SortOrder
  winningPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  description?: Prisma.SortOrder
  requirements?: Prisma.SortOrder
  _count?: Prisma.ContractCountOrderByAggregateInput
  _avg?: Prisma.ContractAvgOrderByAggregateInput
  _max?: Prisma.ContractMaxOrderByAggregateInput
  _min?: Prisma.ContractMinOrderByAggregateInput
  _sum?: Prisma.ContractSumOrderByAggregateInput
}

export type ContractScalarWhereWithAggregatesInput = {
  AND?: Prisma.ContractScalarWhereWithAggregatesInput | Prisma.ContractScalarWhereWithAggregatesInput[]
  OR?: Prisma.ContractScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ContractScalarWhereWithAggregatesInput | Prisma.ContractScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Contract"> | number
  weight?: Prisma.FloatWithAggregatesFilter<"Contract"> | number
  pickupDate?: Prisma.DateTimeWithAggregatesFilter<"Contract"> | Date | string
  dropDate?: Prisma.DateTimeWithAggregatesFilter<"Contract"> | Date | string
  startLocation?: Prisma.StringWithAggregatesFilter<"Contract"> | string
  endLocation?: Prisma.StringWithAggregatesFilter<"Contract"> | string
  approxKms?: Prisma.IntWithAggregatesFilter<"Contract"> | number
  contractorId?: Prisma.IntWithAggregatesFilter<"Contract"> | number
  goodsCarrierId?: Prisma.IntNullableWithAggregatesFilter<"Contract"> | number | null
  typeOfVehicle?: Prisma.EnumVehicleWheelWithAggregatesFilter<"Contract"> | $Enums.VehicleWheel
  insured?: Prisma.BoolWithAggregatesFilter<"Contract"> | boolean
  winningPrice?: Prisma.IntNullableWithAggregatesFilter<"Contract"> | number | null
  type?: Prisma.EnumGoodsTypeWithAggregatesFilter<"Contract"> | $Enums.GoodsType
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Contract"> | Date | string
  description?: Prisma.StringWithAggregatesFilter<"Contract"> | string
  requirements?: Prisma.StringNullableListFilter<"Contract">
}

export type ContractCreateInput = {
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
  contractor: Prisma.UserCreateNestedOneWithoutContractsCreatedInput
  goodsCarrier?: Prisma.UserCreateNestedOneWithoutContractsCarriedInput
  bids?: Prisma.BidCreateNestedManyWithoutContractInput
  insurance?: Prisma.InsuranceCreateNestedOneWithoutContractInput
}

export type ContractUncheckedCreateInput = {
  id?: number
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  contractorId: number
  goodsCarrierId?: number | null
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
  bids?: Prisma.BidUncheckedCreateNestedManyWithoutContractInput
  insurance?: Prisma.InsuranceUncheckedCreateNestedOneWithoutContractInput
}

export type ContractUpdateInput = {
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
  contractor?: Prisma.UserUpdateOneRequiredWithoutContractsCreatedNestedInput
  goodsCarrier?: Prisma.UserUpdateOneWithoutContractsCarriedNestedInput
  bids?: Prisma.BidUpdateManyWithoutContractNestedInput
  insurance?: Prisma.InsuranceUpdateOneWithoutContractNestedInput
}

export type ContractUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  contractorId?: Prisma.IntFieldUpdateOperationsInput | number
  goodsCarrierId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
  bids?: Prisma.BidUncheckedUpdateManyWithoutContractNestedInput
  insurance?: Prisma.InsuranceUncheckedUpdateOneWithoutContractNestedInput
}

export type ContractCreateManyInput = {
  id?: number
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  contractorId: number
  goodsCarrierId?: number | null
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
}

export type ContractUpdateManyMutationInput = {
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
}

export type ContractUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  contractorId?: Prisma.IntFieldUpdateOperationsInput | number
  goodsCarrierId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
}

export type ContractListRelationFilter = {
  every?: Prisma.ContractWhereInput
  some?: Prisma.ContractWhereInput
  none?: Prisma.ContractWhereInput
}

export type ContractOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type ContractCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  pickupDate?: Prisma.SortOrder
  dropDate?: Prisma.SortOrder
  startLocation?: Prisma.SortOrder
  endLocation?: Prisma.SortOrder
  approxKms?: Prisma.SortOrder
  contractorId?: Prisma.SortOrder
  goodsCarrierId?: Prisma.SortOrder
  typeOfVehicle?: Prisma.SortOrder
  insured?: Prisma.SortOrder
  winningPrice?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  description?: Prisma.SortOrder
  requirements?: Prisma.SortOrder
}

export type ContractAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  approxKms?: Prisma.SortOrder
  contractorId?: Prisma.SortOrder
  goodsCarrierId?: Prisma.SortOrder
  winningPrice?: Prisma.SortOrder
}

export type ContractMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  pickupDate?: Prisma.SortOrder
  dropDate?: Prisma.SortOrder
  startLocation?: Prisma.SortOrder
  endLocation?: Prisma.SortOrder
  approxKms?: Prisma.SortOrder
  contractorId?: Prisma.SortOrder
  goodsCarrierId?: Prisma.SortOrder
  typeOfVehicle?: Prisma.SortOrder
  insured?: Prisma.SortOrder
  winningPrice?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ContractMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  pickupDate?: Prisma.SortOrder
  dropDate?: Prisma.SortOrder
  startLocation?: Prisma.SortOrder
  endLocation?: Prisma.SortOrder
  approxKms?: Prisma.SortOrder
  contractorId?: Prisma.SortOrder
  goodsCarrierId?: Prisma.SortOrder
  typeOfVehicle?: Prisma.SortOrder
  insured?: Prisma.SortOrder
  winningPrice?: Prisma.SortOrder
  type?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type ContractSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  weight?: Prisma.SortOrder
  approxKms?: Prisma.SortOrder
  contractorId?: Prisma.SortOrder
  goodsCarrierId?: Prisma.SortOrder
  winningPrice?: Prisma.SortOrder
}

export type ContractScalarRelationFilter = {
  is?: Prisma.ContractWhereInput
  isNot?: Prisma.ContractWhereInput
}

export type ContractCreateNestedManyWithoutContractorInput = {
  create?: Prisma.XOR<Prisma.ContractCreateWithoutContractorInput, Prisma.ContractUncheckedCreateWithoutContractorInput> | Prisma.ContractCreateWithoutContractorInput[] | Prisma.ContractUncheckedCreateWithoutContractorInput[]
  connectOrCreate?: Prisma.ContractCreateOrConnectWithoutContractorInput | Prisma.ContractCreateOrConnectWithoutContractorInput[]
  createMany?: Prisma.ContractCreateManyContractorInputEnvelope
  connect?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
}

export type ContractCreateNestedManyWithoutGoodsCarrierInput = {
  create?: Prisma.XOR<Prisma.ContractCreateWithoutGoodsCarrierInput, Prisma.ContractUncheckedCreateWithoutGoodsCarrierInput> | Prisma.ContractCreateWithoutGoodsCarrierInput[] | Prisma.ContractUncheckedCreateWithoutGoodsCarrierInput[]
  connectOrCreate?: Prisma.ContractCreateOrConnectWithoutGoodsCarrierInput | Prisma.ContractCreateOrConnectWithoutGoodsCarrierInput[]
  createMany?: Prisma.ContractCreateManyGoodsCarrierInputEnvelope
  connect?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
}

export type ContractUncheckedCreateNestedManyWithoutContractorInput = {
  create?: Prisma.XOR<Prisma.ContractCreateWithoutContractorInput, Prisma.ContractUncheckedCreateWithoutContractorInput> | Prisma.ContractCreateWithoutContractorInput[] | Prisma.ContractUncheckedCreateWithoutContractorInput[]
  connectOrCreate?: Prisma.ContractCreateOrConnectWithoutContractorInput | Prisma.ContractCreateOrConnectWithoutContractorInput[]
  createMany?: Prisma.ContractCreateManyContractorInputEnvelope
  connect?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
}

export type ContractUncheckedCreateNestedManyWithoutGoodsCarrierInput = {
  create?: Prisma.XOR<Prisma.ContractCreateWithoutGoodsCarrierInput, Prisma.ContractUncheckedCreateWithoutGoodsCarrierInput> | Prisma.ContractCreateWithoutGoodsCarrierInput[] | Prisma.ContractUncheckedCreateWithoutGoodsCarrierInput[]
  connectOrCreate?: Prisma.ContractCreateOrConnectWithoutGoodsCarrierInput | Prisma.ContractCreateOrConnectWithoutGoodsCarrierInput[]
  createMany?: Prisma.ContractCreateManyGoodsCarrierInputEnvelope
  connect?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
}

export type ContractUpdateManyWithoutContractorNestedInput = {
  create?: Prisma.XOR<Prisma.ContractCreateWithoutContractorInput, Prisma.ContractUncheckedCreateWithoutContractorInput> | Prisma.ContractCreateWithoutContractorInput[] | Prisma.ContractUncheckedCreateWithoutContractorInput[]
  connectOrCreate?: Prisma.ContractCreateOrConnectWithoutContractorInput | Prisma.ContractCreateOrConnectWithoutContractorInput[]
  upsert?: Prisma.ContractUpsertWithWhereUniqueWithoutContractorInput | Prisma.ContractUpsertWithWhereUniqueWithoutContractorInput[]
  createMany?: Prisma.ContractCreateManyContractorInputEnvelope
  set?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  disconnect?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  delete?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  connect?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  update?: Prisma.ContractUpdateWithWhereUniqueWithoutContractorInput | Prisma.ContractUpdateWithWhereUniqueWithoutContractorInput[]
  updateMany?: Prisma.ContractUpdateManyWithWhereWithoutContractorInput | Prisma.ContractUpdateManyWithWhereWithoutContractorInput[]
  deleteMany?: Prisma.ContractScalarWhereInput | Prisma.ContractScalarWhereInput[]
}

export type ContractUpdateManyWithoutGoodsCarrierNestedInput = {
  create?: Prisma.XOR<Prisma.ContractCreateWithoutGoodsCarrierInput, Prisma.ContractUncheckedCreateWithoutGoodsCarrierInput> | Prisma.ContractCreateWithoutGoodsCarrierInput[] | Prisma.ContractUncheckedCreateWithoutGoodsCarrierInput[]
  connectOrCreate?: Prisma.ContractCreateOrConnectWithoutGoodsCarrierInput | Prisma.ContractCreateOrConnectWithoutGoodsCarrierInput[]
  upsert?: Prisma.ContractUpsertWithWhereUniqueWithoutGoodsCarrierInput | Prisma.ContractUpsertWithWhereUniqueWithoutGoodsCarrierInput[]
  createMany?: Prisma.ContractCreateManyGoodsCarrierInputEnvelope
  set?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  disconnect?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  delete?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  connect?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  update?: Prisma.ContractUpdateWithWhereUniqueWithoutGoodsCarrierInput | Prisma.ContractUpdateWithWhereUniqueWithoutGoodsCarrierInput[]
  updateMany?: Prisma.ContractUpdateManyWithWhereWithoutGoodsCarrierInput | Prisma.ContractUpdateManyWithWhereWithoutGoodsCarrierInput[]
  deleteMany?: Prisma.ContractScalarWhereInput | Prisma.ContractScalarWhereInput[]
}

export type ContractUncheckedUpdateManyWithoutContractorNestedInput = {
  create?: Prisma.XOR<Prisma.ContractCreateWithoutContractorInput, Prisma.ContractUncheckedCreateWithoutContractorInput> | Prisma.ContractCreateWithoutContractorInput[] | Prisma.ContractUncheckedCreateWithoutContractorInput[]
  connectOrCreate?: Prisma.ContractCreateOrConnectWithoutContractorInput | Prisma.ContractCreateOrConnectWithoutContractorInput[]
  upsert?: Prisma.ContractUpsertWithWhereUniqueWithoutContractorInput | Prisma.ContractUpsertWithWhereUniqueWithoutContractorInput[]
  createMany?: Prisma.ContractCreateManyContractorInputEnvelope
  set?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  disconnect?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  delete?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  connect?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  update?: Prisma.ContractUpdateWithWhereUniqueWithoutContractorInput | Prisma.ContractUpdateWithWhereUniqueWithoutContractorInput[]
  updateMany?: Prisma.ContractUpdateManyWithWhereWithoutContractorInput | Prisma.ContractUpdateManyWithWhereWithoutContractorInput[]
  deleteMany?: Prisma.ContractScalarWhereInput | Prisma.ContractScalarWhereInput[]
}

export type ContractUncheckedUpdateManyWithoutGoodsCarrierNestedInput = {
  create?: Prisma.XOR<Prisma.ContractCreateWithoutGoodsCarrierInput, Prisma.ContractUncheckedCreateWithoutGoodsCarrierInput> | Prisma.ContractCreateWithoutGoodsCarrierInput[] | Prisma.ContractUncheckedCreateWithoutGoodsCarrierInput[]
  connectOrCreate?: Prisma.ContractCreateOrConnectWithoutGoodsCarrierInput | Prisma.ContractCreateOrConnectWithoutGoodsCarrierInput[]
  upsert?: Prisma.ContractUpsertWithWhereUniqueWithoutGoodsCarrierInput | Prisma.ContractUpsertWithWhereUniqueWithoutGoodsCarrierInput[]
  createMany?: Prisma.ContractCreateManyGoodsCarrierInputEnvelope
  set?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  disconnect?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  delete?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  connect?: Prisma.ContractWhereUniqueInput | Prisma.ContractWhereUniqueInput[]
  update?: Prisma.ContractUpdateWithWhereUniqueWithoutGoodsCarrierInput | Prisma.ContractUpdateWithWhereUniqueWithoutGoodsCarrierInput[]
  updateMany?: Prisma.ContractUpdateManyWithWhereWithoutGoodsCarrierInput | Prisma.ContractUpdateManyWithWhereWithoutGoodsCarrierInput[]
  deleteMany?: Prisma.ContractScalarWhereInput | Prisma.ContractScalarWhereInput[]
}

export type ContractCreaterequirementsInput = {
  set: string[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type EnumVehicleWheelFieldUpdateOperationsInput = {
  set?: $Enums.VehicleWheel
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EnumGoodsTypeFieldUpdateOperationsInput = {
  set?: $Enums.GoodsType
}

export type ContractUpdaterequirementsInput = {
  set?: string[]
  push?: string | string[]
}

export type ContractCreateNestedOneWithoutBidsInput = {
  create?: Prisma.XOR<Prisma.ContractCreateWithoutBidsInput, Prisma.ContractUncheckedCreateWithoutBidsInput>
  connectOrCreate?: Prisma.ContractCreateOrConnectWithoutBidsInput
  connect?: Prisma.ContractWhereUniqueInput
}

export type ContractUpdateOneRequiredWithoutBidsNestedInput = {
  create?: Prisma.XOR<Prisma.ContractCreateWithoutBidsInput, Prisma.ContractUncheckedCreateWithoutBidsInput>
  connectOrCreate?: Prisma.ContractCreateOrConnectWithoutBidsInput
  upsert?: Prisma.ContractUpsertWithoutBidsInput
  connect?: Prisma.ContractWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ContractUpdateToOneWithWhereWithoutBidsInput, Prisma.ContractUpdateWithoutBidsInput>, Prisma.ContractUncheckedUpdateWithoutBidsInput>
}

export type ContractCreateNestedOneWithoutInsuranceInput = {
  create?: Prisma.XOR<Prisma.ContractCreateWithoutInsuranceInput, Prisma.ContractUncheckedCreateWithoutInsuranceInput>
  connectOrCreate?: Prisma.ContractCreateOrConnectWithoutInsuranceInput
  connect?: Prisma.ContractWhereUniqueInput
}

export type ContractUpdateOneRequiredWithoutInsuranceNestedInput = {
  create?: Prisma.XOR<Prisma.ContractCreateWithoutInsuranceInput, Prisma.ContractUncheckedCreateWithoutInsuranceInput>
  connectOrCreate?: Prisma.ContractCreateOrConnectWithoutInsuranceInput
  upsert?: Prisma.ContractUpsertWithoutInsuranceInput
  connect?: Prisma.ContractWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ContractUpdateToOneWithWhereWithoutInsuranceInput, Prisma.ContractUpdateWithoutInsuranceInput>, Prisma.ContractUncheckedUpdateWithoutInsuranceInput>
}

export type ContractCreateWithoutContractorInput = {
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
  goodsCarrier?: Prisma.UserCreateNestedOneWithoutContractsCarriedInput
  bids?: Prisma.BidCreateNestedManyWithoutContractInput
  insurance?: Prisma.InsuranceCreateNestedOneWithoutContractInput
}

export type ContractUncheckedCreateWithoutContractorInput = {
  id?: number
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  goodsCarrierId?: number | null
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
  bids?: Prisma.BidUncheckedCreateNestedManyWithoutContractInput
  insurance?: Prisma.InsuranceUncheckedCreateNestedOneWithoutContractInput
}

export type ContractCreateOrConnectWithoutContractorInput = {
  where: Prisma.ContractWhereUniqueInput
  create: Prisma.XOR<Prisma.ContractCreateWithoutContractorInput, Prisma.ContractUncheckedCreateWithoutContractorInput>
}

export type ContractCreateManyContractorInputEnvelope = {
  data: Prisma.ContractCreateManyContractorInput | Prisma.ContractCreateManyContractorInput[]
  skipDuplicates?: boolean
}

export type ContractCreateWithoutGoodsCarrierInput = {
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
  contractor: Prisma.UserCreateNestedOneWithoutContractsCreatedInput
  bids?: Prisma.BidCreateNestedManyWithoutContractInput
  insurance?: Prisma.InsuranceCreateNestedOneWithoutContractInput
}

export type ContractUncheckedCreateWithoutGoodsCarrierInput = {
  id?: number
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  contractorId: number
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
  bids?: Prisma.BidUncheckedCreateNestedManyWithoutContractInput
  insurance?: Prisma.InsuranceUncheckedCreateNestedOneWithoutContractInput
}

export type ContractCreateOrConnectWithoutGoodsCarrierInput = {
  where: Prisma.ContractWhereUniqueInput
  create: Prisma.XOR<Prisma.ContractCreateWithoutGoodsCarrierInput, Prisma.ContractUncheckedCreateWithoutGoodsCarrierInput>
}

export type ContractCreateManyGoodsCarrierInputEnvelope = {
  data: Prisma.ContractCreateManyGoodsCarrierInput | Prisma.ContractCreateManyGoodsCarrierInput[]
  skipDuplicates?: boolean
}

export type ContractUpsertWithWhereUniqueWithoutContractorInput = {
  where: Prisma.ContractWhereUniqueInput
  update: Prisma.XOR<Prisma.ContractUpdateWithoutContractorInput, Prisma.ContractUncheckedUpdateWithoutContractorInput>
  create: Prisma.XOR<Prisma.ContractCreateWithoutContractorInput, Prisma.ContractUncheckedCreateWithoutContractorInput>
}

export type ContractUpdateWithWhereUniqueWithoutContractorInput = {
  where: Prisma.ContractWhereUniqueInput
  data: Prisma.XOR<Prisma.ContractUpdateWithoutContractorInput, Prisma.ContractUncheckedUpdateWithoutContractorInput>
}

export type ContractUpdateManyWithWhereWithoutContractorInput = {
  where: Prisma.ContractScalarWhereInput
  data: Prisma.XOR<Prisma.ContractUpdateManyMutationInput, Prisma.ContractUncheckedUpdateManyWithoutContractorInput>
}

export type ContractScalarWhereInput = {
  AND?: Prisma.ContractScalarWhereInput | Prisma.ContractScalarWhereInput[]
  OR?: Prisma.ContractScalarWhereInput[]
  NOT?: Prisma.ContractScalarWhereInput | Prisma.ContractScalarWhereInput[]
  id?: Prisma.IntFilter<"Contract"> | number
  weight?: Prisma.FloatFilter<"Contract"> | number
  pickupDate?: Prisma.DateTimeFilter<"Contract"> | Date | string
  dropDate?: Prisma.DateTimeFilter<"Contract"> | Date | string
  startLocation?: Prisma.StringFilter<"Contract"> | string
  endLocation?: Prisma.StringFilter<"Contract"> | string
  approxKms?: Prisma.IntFilter<"Contract"> | number
  contractorId?: Prisma.IntFilter<"Contract"> | number
  goodsCarrierId?: Prisma.IntNullableFilter<"Contract"> | number | null
  typeOfVehicle?: Prisma.EnumVehicleWheelFilter<"Contract"> | $Enums.VehicleWheel
  insured?: Prisma.BoolFilter<"Contract"> | boolean
  winningPrice?: Prisma.IntNullableFilter<"Contract"> | number | null
  type?: Prisma.EnumGoodsTypeFilter<"Contract"> | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFilter<"Contract"> | Date | string
  description?: Prisma.StringFilter<"Contract"> | string
  requirements?: Prisma.StringNullableListFilter<"Contract">
}

export type ContractUpsertWithWhereUniqueWithoutGoodsCarrierInput = {
  where: Prisma.ContractWhereUniqueInput
  update: Prisma.XOR<Prisma.ContractUpdateWithoutGoodsCarrierInput, Prisma.ContractUncheckedUpdateWithoutGoodsCarrierInput>
  create: Prisma.XOR<Prisma.ContractCreateWithoutGoodsCarrierInput, Prisma.ContractUncheckedCreateWithoutGoodsCarrierInput>
}

export type ContractUpdateWithWhereUniqueWithoutGoodsCarrierInput = {
  where: Prisma.ContractWhereUniqueInput
  data: Prisma.XOR<Prisma.ContractUpdateWithoutGoodsCarrierInput, Prisma.ContractUncheckedUpdateWithoutGoodsCarrierInput>
}

export type ContractUpdateManyWithWhereWithoutGoodsCarrierInput = {
  where: Prisma.ContractScalarWhereInput
  data: Prisma.XOR<Prisma.ContractUpdateManyMutationInput, Prisma.ContractUncheckedUpdateManyWithoutGoodsCarrierInput>
}

export type ContractCreateWithoutBidsInput = {
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
  contractor: Prisma.UserCreateNestedOneWithoutContractsCreatedInput
  goodsCarrier?: Prisma.UserCreateNestedOneWithoutContractsCarriedInput
  insurance?: Prisma.InsuranceCreateNestedOneWithoutContractInput
}

export type ContractUncheckedCreateWithoutBidsInput = {
  id?: number
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  contractorId: number
  goodsCarrierId?: number | null
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
  insurance?: Prisma.InsuranceUncheckedCreateNestedOneWithoutContractInput
}

export type ContractCreateOrConnectWithoutBidsInput = {
  where: Prisma.ContractWhereUniqueInput
  create: Prisma.XOR<Prisma.ContractCreateWithoutBidsInput, Prisma.ContractUncheckedCreateWithoutBidsInput>
}

export type ContractUpsertWithoutBidsInput = {
  update: Prisma.XOR<Prisma.ContractUpdateWithoutBidsInput, Prisma.ContractUncheckedUpdateWithoutBidsInput>
  create: Prisma.XOR<Prisma.ContractCreateWithoutBidsInput, Prisma.ContractUncheckedCreateWithoutBidsInput>
  where?: Prisma.ContractWhereInput
}

export type ContractUpdateToOneWithWhereWithoutBidsInput = {
  where?: Prisma.ContractWhereInput
  data: Prisma.XOR<Prisma.ContractUpdateWithoutBidsInput, Prisma.ContractUncheckedUpdateWithoutBidsInput>
}

export type ContractUpdateWithoutBidsInput = {
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
  contractor?: Prisma.UserUpdateOneRequiredWithoutContractsCreatedNestedInput
  goodsCarrier?: Prisma.UserUpdateOneWithoutContractsCarriedNestedInput
  insurance?: Prisma.InsuranceUpdateOneWithoutContractNestedInput
}

export type ContractUncheckedUpdateWithoutBidsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  contractorId?: Prisma.IntFieldUpdateOperationsInput | number
  goodsCarrierId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
  insurance?: Prisma.InsuranceUncheckedUpdateOneWithoutContractNestedInput
}

export type ContractCreateWithoutInsuranceInput = {
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
  contractor: Prisma.UserCreateNestedOneWithoutContractsCreatedInput
  goodsCarrier?: Prisma.UserCreateNestedOneWithoutContractsCarriedInput
  bids?: Prisma.BidCreateNestedManyWithoutContractInput
}

export type ContractUncheckedCreateWithoutInsuranceInput = {
  id?: number
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  contractorId: number
  goodsCarrierId?: number | null
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
  bids?: Prisma.BidUncheckedCreateNestedManyWithoutContractInput
}

export type ContractCreateOrConnectWithoutInsuranceInput = {
  where: Prisma.ContractWhereUniqueInput
  create: Prisma.XOR<Prisma.ContractCreateWithoutInsuranceInput, Prisma.ContractUncheckedCreateWithoutInsuranceInput>
}

export type ContractUpsertWithoutInsuranceInput = {
  update: Prisma.XOR<Prisma.ContractUpdateWithoutInsuranceInput, Prisma.ContractUncheckedUpdateWithoutInsuranceInput>
  create: Prisma.XOR<Prisma.ContractCreateWithoutInsuranceInput, Prisma.ContractUncheckedCreateWithoutInsuranceInput>
  where?: Prisma.ContractWhereInput
}

export type ContractUpdateToOneWithWhereWithoutInsuranceInput = {
  where?: Prisma.ContractWhereInput
  data: Prisma.XOR<Prisma.ContractUpdateWithoutInsuranceInput, Prisma.ContractUncheckedUpdateWithoutInsuranceInput>
}

export type ContractUpdateWithoutInsuranceInput = {
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
  contractor?: Prisma.UserUpdateOneRequiredWithoutContractsCreatedNestedInput
  goodsCarrier?: Prisma.UserUpdateOneWithoutContractsCarriedNestedInput
  bids?: Prisma.BidUpdateManyWithoutContractNestedInput
}

export type ContractUncheckedUpdateWithoutInsuranceInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  contractorId?: Prisma.IntFieldUpdateOperationsInput | number
  goodsCarrierId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
  bids?: Prisma.BidUncheckedUpdateManyWithoutContractNestedInput
}

export type ContractCreateManyContractorInput = {
  id?: number
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  goodsCarrierId?: number | null
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
}

export type ContractCreateManyGoodsCarrierInput = {
  id?: number
  weight: number
  pickupDate: Date | string
  dropDate: Date | string
  startLocation: string
  endLocation: string
  approxKms: number
  contractorId: number
  typeOfVehicle: $Enums.VehicleWheel
  insured: boolean
  winningPrice?: number | null
  type: $Enums.GoodsType
  createdAt?: Date | string
  description?: string
  requirements?: Prisma.ContractCreaterequirementsInput | string[]
}

export type ContractUpdateWithoutContractorInput = {
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
  goodsCarrier?: Prisma.UserUpdateOneWithoutContractsCarriedNestedInput
  bids?: Prisma.BidUpdateManyWithoutContractNestedInput
  insurance?: Prisma.InsuranceUpdateOneWithoutContractNestedInput
}

export type ContractUncheckedUpdateWithoutContractorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  goodsCarrierId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
  bids?: Prisma.BidUncheckedUpdateManyWithoutContractNestedInput
  insurance?: Prisma.InsuranceUncheckedUpdateOneWithoutContractNestedInput
}

export type ContractUncheckedUpdateManyWithoutContractorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  goodsCarrierId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
}

export type ContractUpdateWithoutGoodsCarrierInput = {
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
  contractor?: Prisma.UserUpdateOneRequiredWithoutContractsCreatedNestedInput
  bids?: Prisma.BidUpdateManyWithoutContractNestedInput
  insurance?: Prisma.InsuranceUpdateOneWithoutContractNestedInput
}

export type ContractUncheckedUpdateWithoutGoodsCarrierInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  contractorId?: Prisma.IntFieldUpdateOperationsInput | number
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
  bids?: Prisma.BidUncheckedUpdateManyWithoutContractNestedInput
  insurance?: Prisma.InsuranceUncheckedUpdateOneWithoutContractNestedInput
}

export type ContractUncheckedUpdateManyWithoutGoodsCarrierInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  weight?: Prisma.FloatFieldUpdateOperationsInput | number
  pickupDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dropDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startLocation?: Prisma.StringFieldUpdateOperationsInput | string
  endLocation?: Prisma.StringFieldUpdateOperationsInput | string
  approxKms?: Prisma.IntFieldUpdateOperationsInput | number
  contractorId?: Prisma.IntFieldUpdateOperationsInput | number
  typeOfVehicle?: Prisma.EnumVehicleWheelFieldUpdateOperationsInput | $Enums.VehicleWheel
  insured?: Prisma.BoolFieldUpdateOperationsInput | boolean
  winningPrice?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  type?: Prisma.EnumGoodsTypeFieldUpdateOperationsInput | $Enums.GoodsType
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  requirements?: Prisma.ContractUpdaterequirementsInput | string[]
}


/**
 * Count Type ContractCountOutputType
 */

export type ContractCountOutputType = {
  bids: number
}

export type ContractCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bids?: boolean | ContractCountOutputTypeCountBidsArgs
}

/**
 * ContractCountOutputType without action
 */
export type ContractCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContractCountOutputType
   */
  select?: Prisma.ContractCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ContractCountOutputType without action
 */
export type ContractCountOutputTypeCountBidsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BidWhereInput
}


export type ContractSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  weight?: boolean
  pickupDate?: boolean
  dropDate?: boolean
  startLocation?: boolean
  endLocation?: boolean
  approxKms?: boolean
  contractorId?: boolean
  goodsCarrierId?: boolean
  typeOfVehicle?: boolean
  insured?: boolean
  winningPrice?: boolean
  type?: boolean
  createdAt?: boolean
  description?: boolean
  requirements?: boolean
  contractor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  goodsCarrier?: boolean | Prisma.Contract$goodsCarrierArgs<ExtArgs>
  bids?: boolean | Prisma.Contract$bidsArgs<ExtArgs>
  insurance?: boolean | Prisma.Contract$insuranceArgs<ExtArgs>
  _count?: boolean | Prisma.ContractCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["contract"]>

export type ContractSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  weight?: boolean
  pickupDate?: boolean
  dropDate?: boolean
  startLocation?: boolean
  endLocation?: boolean
  approxKms?: boolean
  contractorId?: boolean
  goodsCarrierId?: boolean
  typeOfVehicle?: boolean
  insured?: boolean
  winningPrice?: boolean
  type?: boolean
  createdAt?: boolean
  description?: boolean
  requirements?: boolean
  contractor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  goodsCarrier?: boolean | Prisma.Contract$goodsCarrierArgs<ExtArgs>
}, ExtArgs["result"]["contract"]>

export type ContractSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  weight?: boolean
  pickupDate?: boolean
  dropDate?: boolean
  startLocation?: boolean
  endLocation?: boolean
  approxKms?: boolean
  contractorId?: boolean
  goodsCarrierId?: boolean
  typeOfVehicle?: boolean
  insured?: boolean
  winningPrice?: boolean
  type?: boolean
  createdAt?: boolean
  description?: boolean
  requirements?: boolean
  contractor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  goodsCarrier?: boolean | Prisma.Contract$goodsCarrierArgs<ExtArgs>
}, ExtArgs["result"]["contract"]>

export type ContractSelectScalar = {
  id?: boolean
  weight?: boolean
  pickupDate?: boolean
  dropDate?: boolean
  startLocation?: boolean
  endLocation?: boolean
  approxKms?: boolean
  contractorId?: boolean
  goodsCarrierId?: boolean
  typeOfVehicle?: boolean
  insured?: boolean
  winningPrice?: boolean
  type?: boolean
  createdAt?: boolean
  description?: boolean
  requirements?: boolean
}

export type ContractOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "weight" | "pickupDate" | "dropDate" | "startLocation" | "endLocation" | "approxKms" | "contractorId" | "goodsCarrierId" | "typeOfVehicle" | "insured" | "winningPrice" | "type" | "createdAt" | "description" | "requirements", ExtArgs["result"]["contract"]>
export type ContractInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contractor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  goodsCarrier?: boolean | Prisma.Contract$goodsCarrierArgs<ExtArgs>
  bids?: boolean | Prisma.Contract$bidsArgs<ExtArgs>
  insurance?: boolean | Prisma.Contract$insuranceArgs<ExtArgs>
  _count?: boolean | Prisma.ContractCountOutputTypeDefaultArgs<ExtArgs>
}
export type ContractIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contractor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  goodsCarrier?: boolean | Prisma.Contract$goodsCarrierArgs<ExtArgs>
}
export type ContractIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contractor?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  goodsCarrier?: boolean | Prisma.Contract$goodsCarrierArgs<ExtArgs>
}

export type $ContractPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Contract"
  objects: {
    contractor: Prisma.$UserPayload<ExtArgs>
    goodsCarrier: Prisma.$UserPayload<ExtArgs> | null
    bids: Prisma.$BidPayload<ExtArgs>[]
    insurance: Prisma.$InsurancePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    weight: number
    pickupDate: Date
    dropDate: Date
    startLocation: string
    endLocation: string
    approxKms: number
    contractorId: number
    goodsCarrierId: number | null
    typeOfVehicle: $Enums.VehicleWheel
    insured: boolean
    winningPrice: number | null
    type: $Enums.GoodsType
    createdAt: Date
    description: string
    requirements: string[]
  }, ExtArgs["result"]["contract"]>
  composites: {}
}

export type ContractGetPayload<S extends boolean | null | undefined | ContractDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ContractPayload, S>

export type ContractCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ContractFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ContractCountAggregateInputType | true
  }

export interface ContractDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Contract'], meta: { name: 'Contract' } }
  /**
   * Find zero or one Contract that matches the filter.
   * @param {ContractFindUniqueArgs} args - Arguments to find a Contract
   * @example
   * // Get one Contract
   * const contract = await prisma.contract.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ContractFindUniqueArgs>(args: Prisma.SelectSubset<T, ContractFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ContractClient<runtime.Types.Result.GetResult<Prisma.$ContractPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Contract that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ContractFindUniqueOrThrowArgs} args - Arguments to find a Contract
   * @example
   * // Get one Contract
   * const contract = await prisma.contract.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ContractFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ContractFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContractClient<runtime.Types.Result.GetResult<Prisma.$ContractPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Contract that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContractFindFirstArgs} args - Arguments to find a Contract
   * @example
   * // Get one Contract
   * const contract = await prisma.contract.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ContractFindFirstArgs>(args?: Prisma.SelectSubset<T, ContractFindFirstArgs<ExtArgs>>): Prisma.Prisma__ContractClient<runtime.Types.Result.GetResult<Prisma.$ContractPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Contract that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContractFindFirstOrThrowArgs} args - Arguments to find a Contract
   * @example
   * // Get one Contract
   * const contract = await prisma.contract.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ContractFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ContractFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContractClient<runtime.Types.Result.GetResult<Prisma.$ContractPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Contracts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContractFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Contracts
   * const contracts = await prisma.contract.findMany()
   * 
   * // Get first 10 Contracts
   * const contracts = await prisma.contract.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const contractWithIdOnly = await prisma.contract.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ContractFindManyArgs>(args?: Prisma.SelectSubset<T, ContractFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContractPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Contract.
   * @param {ContractCreateArgs} args - Arguments to create a Contract.
   * @example
   * // Create one Contract
   * const Contract = await prisma.contract.create({
   *   data: {
   *     // ... data to create a Contract
   *   }
   * })
   * 
   */
  create<T extends ContractCreateArgs>(args: Prisma.SelectSubset<T, ContractCreateArgs<ExtArgs>>): Prisma.Prisma__ContractClient<runtime.Types.Result.GetResult<Prisma.$ContractPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Contracts.
   * @param {ContractCreateManyArgs} args - Arguments to create many Contracts.
   * @example
   * // Create many Contracts
   * const contract = await prisma.contract.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ContractCreateManyArgs>(args?: Prisma.SelectSubset<T, ContractCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Contracts and returns the data saved in the database.
   * @param {ContractCreateManyAndReturnArgs} args - Arguments to create many Contracts.
   * @example
   * // Create many Contracts
   * const contract = await prisma.contract.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Contracts and only return the `id`
   * const contractWithIdOnly = await prisma.contract.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ContractCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ContractCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContractPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Contract.
   * @param {ContractDeleteArgs} args - Arguments to delete one Contract.
   * @example
   * // Delete one Contract
   * const Contract = await prisma.contract.delete({
   *   where: {
   *     // ... filter to delete one Contract
   *   }
   * })
   * 
   */
  delete<T extends ContractDeleteArgs>(args: Prisma.SelectSubset<T, ContractDeleteArgs<ExtArgs>>): Prisma.Prisma__ContractClient<runtime.Types.Result.GetResult<Prisma.$ContractPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Contract.
   * @param {ContractUpdateArgs} args - Arguments to update one Contract.
   * @example
   * // Update one Contract
   * const contract = await prisma.contract.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ContractUpdateArgs>(args: Prisma.SelectSubset<T, ContractUpdateArgs<ExtArgs>>): Prisma.Prisma__ContractClient<runtime.Types.Result.GetResult<Prisma.$ContractPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Contracts.
   * @param {ContractDeleteManyArgs} args - Arguments to filter Contracts to delete.
   * @example
   * // Delete a few Contracts
   * const { count } = await prisma.contract.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ContractDeleteManyArgs>(args?: Prisma.SelectSubset<T, ContractDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Contracts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContractUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Contracts
   * const contract = await prisma.contract.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ContractUpdateManyArgs>(args: Prisma.SelectSubset<T, ContractUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Contracts and returns the data updated in the database.
   * @param {ContractUpdateManyAndReturnArgs} args - Arguments to update many Contracts.
   * @example
   * // Update many Contracts
   * const contract = await prisma.contract.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Contracts and only return the `id`
   * const contractWithIdOnly = await prisma.contract.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ContractUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ContractUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContractPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Contract.
   * @param {ContractUpsertArgs} args - Arguments to update or create a Contract.
   * @example
   * // Update or create a Contract
   * const contract = await prisma.contract.upsert({
   *   create: {
   *     // ... data to create a Contract
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Contract we want to update
   *   }
   * })
   */
  upsert<T extends ContractUpsertArgs>(args: Prisma.SelectSubset<T, ContractUpsertArgs<ExtArgs>>): Prisma.Prisma__ContractClient<runtime.Types.Result.GetResult<Prisma.$ContractPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Contracts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContractCountArgs} args - Arguments to filter Contracts to count.
   * @example
   * // Count the number of Contracts
   * const count = await prisma.contract.count({
   *   where: {
   *     // ... the filter for the Contracts we want to count
   *   }
   * })
  **/
  count<T extends ContractCountArgs>(
    args?: Prisma.Subset<T, ContractCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ContractCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Contract.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContractAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ContractAggregateArgs>(args: Prisma.Subset<T, ContractAggregateArgs>): Prisma.PrismaPromise<GetContractAggregateType<T>>

  /**
   * Group by Contract.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContractGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ContractGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ContractGroupByArgs['orderBy'] }
      : { orderBy?: ContractGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ContractGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetContractGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Contract model
 */
readonly fields: ContractFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Contract.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ContractClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  contractor<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  goodsCarrier<T extends Prisma.Contract$goodsCarrierArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Contract$goodsCarrierArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  bids<T extends Prisma.Contract$bidsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Contract$bidsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BidPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  insurance<T extends Prisma.Contract$insuranceArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Contract$insuranceArgs<ExtArgs>>): Prisma.Prisma__InsuranceClient<runtime.Types.Result.GetResult<Prisma.$InsurancePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Contract model
 */
export interface ContractFieldRefs {
  readonly id: Prisma.FieldRef<"Contract", 'Int'>
  readonly weight: Prisma.FieldRef<"Contract", 'Float'>
  readonly pickupDate: Prisma.FieldRef<"Contract", 'DateTime'>
  readonly dropDate: Prisma.FieldRef<"Contract", 'DateTime'>
  readonly startLocation: Prisma.FieldRef<"Contract", 'String'>
  readonly endLocation: Prisma.FieldRef<"Contract", 'String'>
  readonly approxKms: Prisma.FieldRef<"Contract", 'Int'>
  readonly contractorId: Prisma.FieldRef<"Contract", 'Int'>
  readonly goodsCarrierId: Prisma.FieldRef<"Contract", 'Int'>
  readonly typeOfVehicle: Prisma.FieldRef<"Contract", 'VehicleWheel'>
  readonly insured: Prisma.FieldRef<"Contract", 'Boolean'>
  readonly winningPrice: Prisma.FieldRef<"Contract", 'Int'>
  readonly type: Prisma.FieldRef<"Contract", 'GoodsType'>
  readonly createdAt: Prisma.FieldRef<"Contract", 'DateTime'>
  readonly description: Prisma.FieldRef<"Contract", 'String'>
  readonly requirements: Prisma.FieldRef<"Contract", 'String[]'>
}
    

// Custom InputTypes
/**
 * Contract findUnique
 */
export type ContractFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contract
   */
  select?: Prisma.ContractSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contract
   */
  omit?: Prisma.ContractOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContractInclude<ExtArgs> | null
  /**
   * Filter, which Contract to fetch.
   */
  where: Prisma.ContractWhereUniqueInput
}

/**
 * Contract findUniqueOrThrow
 */
export type ContractFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contract
   */
  select?: Prisma.ContractSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contract
   */
  omit?: Prisma.ContractOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContractInclude<ExtArgs> | null
  /**
   * Filter, which Contract to fetch.
   */
  where: Prisma.ContractWhereUniqueInput
}

/**
 * Contract findFirst
 */
export type ContractFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contract
   */
  select?: Prisma.ContractSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contract
   */
  omit?: Prisma.ContractOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContractInclude<ExtArgs> | null
  /**
   * Filter, which Contract to fetch.
   */
  where?: Prisma.ContractWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contracts to fetch.
   */
  orderBy?: Prisma.ContractOrderByWithRelationInput | Prisma.ContractOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Contracts.
   */
  cursor?: Prisma.ContractWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contracts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contracts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Contracts.
   */
  distinct?: Prisma.ContractScalarFieldEnum | Prisma.ContractScalarFieldEnum[]
}

/**
 * Contract findFirstOrThrow
 */
export type ContractFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contract
   */
  select?: Prisma.ContractSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contract
   */
  omit?: Prisma.ContractOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContractInclude<ExtArgs> | null
  /**
   * Filter, which Contract to fetch.
   */
  where?: Prisma.ContractWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contracts to fetch.
   */
  orderBy?: Prisma.ContractOrderByWithRelationInput | Prisma.ContractOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Contracts.
   */
  cursor?: Prisma.ContractWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contracts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contracts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Contracts.
   */
  distinct?: Prisma.ContractScalarFieldEnum | Prisma.ContractScalarFieldEnum[]
}

/**
 * Contract findMany
 */
export type ContractFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contract
   */
  select?: Prisma.ContractSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contract
   */
  omit?: Prisma.ContractOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContractInclude<ExtArgs> | null
  /**
   * Filter, which Contracts to fetch.
   */
  where?: Prisma.ContractWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Contracts to fetch.
   */
  orderBy?: Prisma.ContractOrderByWithRelationInput | Prisma.ContractOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Contracts.
   */
  cursor?: Prisma.ContractWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Contracts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Contracts.
   */
  skip?: number
  distinct?: Prisma.ContractScalarFieldEnum | Prisma.ContractScalarFieldEnum[]
}

/**
 * Contract create
 */
export type ContractCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contract
   */
  select?: Prisma.ContractSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contract
   */
  omit?: Prisma.ContractOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContractInclude<ExtArgs> | null
  /**
   * The data needed to create a Contract.
   */
  data: Prisma.XOR<Prisma.ContractCreateInput, Prisma.ContractUncheckedCreateInput>
}

/**
 * Contract createMany
 */
export type ContractCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Contracts.
   */
  data: Prisma.ContractCreateManyInput | Prisma.ContractCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Contract createManyAndReturn
 */
export type ContractCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contract
   */
  select?: Prisma.ContractSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Contract
   */
  omit?: Prisma.ContractOmit<ExtArgs> | null
  /**
   * The data used to create many Contracts.
   */
  data: Prisma.ContractCreateManyInput | Prisma.ContractCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContractIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Contract update
 */
export type ContractUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contract
   */
  select?: Prisma.ContractSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contract
   */
  omit?: Prisma.ContractOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContractInclude<ExtArgs> | null
  /**
   * The data needed to update a Contract.
   */
  data: Prisma.XOR<Prisma.ContractUpdateInput, Prisma.ContractUncheckedUpdateInput>
  /**
   * Choose, which Contract to update.
   */
  where: Prisma.ContractWhereUniqueInput
}

/**
 * Contract updateMany
 */
export type ContractUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Contracts.
   */
  data: Prisma.XOR<Prisma.ContractUpdateManyMutationInput, Prisma.ContractUncheckedUpdateManyInput>
  /**
   * Filter which Contracts to update
   */
  where?: Prisma.ContractWhereInput
  /**
   * Limit how many Contracts to update.
   */
  limit?: number
}

/**
 * Contract updateManyAndReturn
 */
export type ContractUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contract
   */
  select?: Prisma.ContractSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Contract
   */
  omit?: Prisma.ContractOmit<ExtArgs> | null
  /**
   * The data used to update Contracts.
   */
  data: Prisma.XOR<Prisma.ContractUpdateManyMutationInput, Prisma.ContractUncheckedUpdateManyInput>
  /**
   * Filter which Contracts to update
   */
  where?: Prisma.ContractWhereInput
  /**
   * Limit how many Contracts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContractIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Contract upsert
 */
export type ContractUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contract
   */
  select?: Prisma.ContractSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contract
   */
  omit?: Prisma.ContractOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContractInclude<ExtArgs> | null
  /**
   * The filter to search for the Contract to update in case it exists.
   */
  where: Prisma.ContractWhereUniqueInput
  /**
   * In case the Contract found by the `where` argument doesn't exist, create a new Contract with this data.
   */
  create: Prisma.XOR<Prisma.ContractCreateInput, Prisma.ContractUncheckedCreateInput>
  /**
   * In case the Contract was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ContractUpdateInput, Prisma.ContractUncheckedUpdateInput>
}

/**
 * Contract delete
 */
export type ContractDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contract
   */
  select?: Prisma.ContractSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contract
   */
  omit?: Prisma.ContractOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContractInclude<ExtArgs> | null
  /**
   * Filter which Contract to delete.
   */
  where: Prisma.ContractWhereUniqueInput
}

/**
 * Contract deleteMany
 */
export type ContractDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Contracts to delete
   */
  where?: Prisma.ContractWhereInput
  /**
   * Limit how many Contracts to delete.
   */
  limit?: number
}

/**
 * Contract.goodsCarrier
 */
export type Contract$goodsCarrierArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Contract.bids
 */
export type Contract$bidsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bid
   */
  select?: Prisma.BidSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bid
   */
  omit?: Prisma.BidOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BidInclude<ExtArgs> | null
  where?: Prisma.BidWhereInput
  orderBy?: Prisma.BidOrderByWithRelationInput | Prisma.BidOrderByWithRelationInput[]
  cursor?: Prisma.BidWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BidScalarFieldEnum | Prisma.BidScalarFieldEnum[]
}

/**
 * Contract.insurance
 */
export type Contract$insuranceArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Insurance
   */
  select?: Prisma.InsuranceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Insurance
   */
  omit?: Prisma.InsuranceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InsuranceInclude<ExtArgs> | null
  where?: Prisma.InsuranceWhereInput
}

/**
 * Contract without action
 */
export type ContractDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Contract
   */
  select?: Prisma.ContractSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Contract
   */
  omit?: Prisma.ContractOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContractInclude<ExtArgs> | null
}
